/*You are given a string stored in a variable str, and the length of the string is stored in a variable with the name N

The value stored in N will always be even

You have to make two strings from the given string, such that the first string contains all the characters in the first half, and the second string contains all the characters present in the second half.

For example, if the value stored in N = 6, and str = "ababcb", then the string generated by the characters in the first half is aba, and the string generated by the characters in the second half is bcb. Since, both the strings are palindromes, the output is yes

Note : The string contains only lower case English Alphabets, and the length of the string will always be an even number
*/
function halfPalindrome(N, str) {
    //write code here
    let str1="";
    let str2="";
    for(let i=0;i<N/2;i++)
    {
        str1+=str[i];
    }
    for(let j=(N/2);j<N;j++)
    {
        str2+=str[j];
    }
    if(isPalindromefn(str1)&&isPalindromefn(str2))
    {
        console.log("yes");
    }
    else
    {
        console.log("no");
    }
  }
function isPalindromefn(str) {
    let i=0;
    let j=str.length-1;
    let isPalindrome=true;
    while(i<j)
    {
        if(str[i]!==str[j])
        {
            isPalindrome=false;
            break;
        }
        i++;
        j--;
    }
    return isPalindrome;
}
  halfPalindrome(6,"abaaea")