/* Alan Turing, the mathematician, is trying to break the encrypted messages of the German Troops, generated by their encryption device "Enigma". 
To find the distribution of characters, he needs to find out how many times a particular character appears in a string. But, to feed the data into
 his computer, "Christopher", he needs the data in lexicographic order, that is, in alphabetical order. Since, he is busy making "Christopher" 
 better, he asks you for help. Help Alan find the frequency of characters in the encrypted strings in alphabetical order. The string contains only
  lower case alphabets.
?Input      Output
4           s-1
sidd        i-1
            d-2
*/
function alanFrequency(N, str) {
  //write code here
  let obj = {};
  // code so that the key value will always be in alphabetical order 
  let alpha = "abcdefghijklmnopqrstuvwxyz";
  let string = "";
  for (let i = 0; i < alpha.length; i++) {
    for (let j = 0; j < str.length; j++) {
      if (alpha[i] === str[j]) {
        string += alpha[i];
      }
    }
  }
  //---------------
  for (let i = 0; i < N; i++) {
    if (obj[string[i]] !== undefined) {
      obj[string[i]]++;
    }
    else {
      obj[string[i]] = 1;
    }
    obj[string[i]].sort();
  }
  // console.log(obj);  //s:1 i:1 d:2

  for (let key in obj) {
    console.log(key + "-" + obj[key]);
  }
}
alanFrequency(76, "gfcgqxfxkujvrkjvxeirrsvqdjcejjybwjnexvnmldrfeehotsfvnawqzmztknyywomssgdmllek");

